name: main

on:
  watch:
    types: started
  schedule:
    - cron: "0 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'use Python'
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 'Install dependencies'
      run: pip install -r requirements.txt
    - name: 'rm json xls'
      run: rm -rf json xls
    - name: 'run python'
      run: python main.py
    - name: 'git config'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull
        git add .
        git commit -m "update"
    - name: 'push'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.token }}
    - name: 'create release'
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
      with:
        args: nba98
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{secrets.token}}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: api/public
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
        source-repo: ${{ secrets.source }}
        destination-repo: ${{ secrets.destination }}
    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
        gitee-username: ${{ secrets.user }}
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        gitee-repo: ${{ secrets.repo }}